version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1

workflows:
  lint-pack:
    jobs:
      - test-scripts:
          filters:
            tags:
              only: /.*/
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/review:
          filters:
            tags:
              only: /.*/
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
      - orb-tools/publish:
          orb-name: eld/cachix
          requires:
            [
              test-scripts,
              orb-tools/lint,
              orb-tools/review,
              orb-tools/pack,
              shellcheck/check,
            ]
          vcs-type: << pipeline.project.type >>
          # Use a context to hold your publishing token.
          context: orb-publishing
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]

jobs:
  test-scripts:
    docker:
      - image: nixpkgs/nix:latest
    steps:
      - checkout
      - run:
          name: "Add Default Channel"
          command: |
            mkdir -p /etc/nix /root
            echo "sandbox = false" >> /etc/nix/nix.conf
            nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
            nix-channel --update
      - run:
          name: "Install Rust"
          command: |
            nix-env -iA nixpkgs.rustup nixpkgs.gcc
            rustup install stable
      - run:
          name: "Test xshell scripts"
          command: cargo test
